package org.engine.simulogic.android.circuits.components
enum class CTypes {
    AND,
    OR,
    NOT,
    NAND,
    NOR,
    XOR,
    XNOR,
    CLOCK,
    LATCH,
    WIRE,
    RANDOM,
    LED,
    SIGNAL_IN,
    SIGNAL_OUT,
    D_SIGNAL_IN,
    Q_SIGNAL_OUT,
    E_SIGNAL_IN,
    SIGNAL_RANGE_POINT,
    SEVEN_SEGMENT_DISPLAY,
    LINE_MARKER,
    LABEL,
    POWER,
    DATA_BUS,
    DATA_BUS_FAN_OUT,
    NONE
}
